### PR TITLE
Allow to enable animation on roll period change

### PR DESCRIPTION
**Pull request by masonlouchart**
- remove useless private "_originalRange"
- add possibility to enable/disable animation during date window update (after roll period change)

### CODE REVIEW

**Comment by masonlouchart** [comment]
@reinert Can you review this one please? 📓

**Comment by reinert** [comment]
Sorry, I forgot!
Thanks!

**Comment by reinert** [comment]
Do you need a new release?

**Comment by masonlouchart** [comment]
I would like to contribute a little but I'm not sure to have the time now. As you prefer :)

**Comment by masonlouchart** [comment]
@reinert can you make a new release please? I haven't time to contribute though 😄 .

**Comment by reinert** [comment]
No problem!

**Comment by reinert** [comment]
Done!

**Comment by masonlouchart** [comment]
Thank you! 🎉

**Pull request merged**
