### PR TITLE
Expose the roll period option

### PR DESCRIPTION
**Pull request by masonlouchart**
This PR allows to change easily the "rollPeriod" option of any
graph provided by dygraphs. It adds also a little bit data to
the demos.

### CODE REVIEW

**Comment by reinert** [comment]
Good implementation. 
Thanks for contributing.

**Comment by reinert** [comment]
FYI, a new tag was released with these PRs.

**Comment by masonlouchart** [comment]
If you want I can add the same animation of [this page](http://dygraphs.com/gallery/#g/link-interaction). What do you think ?

**Comment by reinert** [comment]
It would be great!

Em seg, 20 de jun de 2016 às 10:02, Mason Louchart notifications@github.com
escreveu:

**Pull request merged**
